/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Member extends org.jooq.impl.TableImpl<tech.codingclub.helix.tables.records.MemberRecord> {

	private static final long serialVersionUID = -1138698450;

	/**
	 * The singleton instance of <code>public.Member</code>
	 */
	public static final tech.codingclub.helix.tables.Member MEMBER = new tech.codingclub.helix.tables.Member();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<tech.codingclub.helix.tables.records.MemberRecord> getRecordType() {
		return tech.codingclub.helix.tables.records.MemberRecord.class;
	}

	/**
	 * The column <code>public.Member.id</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.MemberRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.Member.name</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.MemberRecord, java.lang.String[]> NAME = createField("name", org.jooq.impl.SQLDataType.CHAR.getArrayDataType(), this, "");

	/**
	 * The column <code>public.Member.email</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.MemberRecord, java.lang.String[]> EMAIL = createField("email", org.jooq.impl.SQLDataType.CHAR.getArrayDataType(), this, "");

	/**
	 * The column <code>public.Member.role</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.MemberRecord, java.lang.String[]> ROLE = createField("role", org.jooq.impl.SQLDataType.CHAR.getArrayDataType(), this, "");

	/**
	 * The column <code>public.Member.password</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.MemberRecord, java.lang.String[]> PASSWORD = createField("password", org.jooq.impl.SQLDataType.CHAR.getArrayDataType(), this, "");

	/**
	 * The column <code>public.Member.image</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.MemberRecord, java.lang.String[]> IMAGE = createField("image", org.jooq.impl.SQLDataType.CHAR.getArrayDataType(), this, "");

	/**
	 * The column <code>public.Member.token</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.MemberRecord, java.lang.String[]> TOKEN = createField("token", org.jooq.impl.SQLDataType.CHAR.getArrayDataType(), this, "");

	/**
	 * The column <code>public.Member.is_verified</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.MemberRecord, java.lang.Boolean> IS_VERIFIED = createField("is_verified", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * Create a <code>public.Member</code> table reference
	 */
	public Member() {
		this("Member", null);
	}

	/**
	 * Create an aliased <code>public.Member</code> table reference
	 */
	public Member(java.lang.String alias) {
		this(alias, tech.codingclub.helix.tables.Member.MEMBER);
	}

	private Member(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.MemberRecord> aliased) {
		this(alias, aliased, null);
	}

	private Member(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.MemberRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, tech.codingclub.helix.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public tech.codingclub.helix.tables.Member as(java.lang.String alias) {
		return new tech.codingclub.helix.tables.Member(alias, this);
	}

	/**
	 * Rename this table
	 */
	public tech.codingclub.helix.tables.Member rename(java.lang.String name) {
		return new tech.codingclub.helix.tables.Member(name, null);
	}
}
